@startuml
'https://plantuml.com/class-diagram
class ToDoApp{
    main()
    start()
}
class ToDoListController{
    -model: ListsMenu

    'GUI event handlers
}

class TodoListModel{
    ToDoItem: ArrayList

    +addItem(String)
    +removeItem(String)
    +searchItem(String): TodoItem
    +editItemTitle(String)
    +editItemDueDate(String)
    +editItemDescription(String)
    +isComplete(Boolean)
    +save()
    +clear()
    +displayIncomplete()
    +displayCompleted()
    +load()
}
class TodoItem{
    description: String
    dueDate: String
    isComplete: Boolean
    title: String

    TodoItem(String,String,String,Boolean)

    +setDescription(String)
    +setTitle(String)
    +setDueDate(String)
    +setIsComplete(Boolean)
    +getDescription()
    +getDueDate()
    +getIsComplete()
    +getTitle()

}

org.javafx.Application <|-- ToDoApp
ToDoApp -- ToDoListController
ToDoListController -- TodoListModel
TodoListModel *-- TodoItem
@enduml